# OAuth Configuration
hwi_oauth:
    firewall_name: main
    http_client:
        verify_peer: false
    resource_owners:
        instagram:
            type:             instagram
            client_id:        "d4aadcb9924a4ec3ad5cbd5b2efc9f18"
            client_secret:    "16f39b3eed154ad39c03334029da83e7"

        vkontakte:
            type:             vkontakte
            client_id:        "4602253"
            client_secret:    "68ZtvU4VMVohGyGk1tjN"
            scope:            "offline,email,photos,audio"

        github:
            type:             github
            client_id:        "d5669f459325404670d1" #"4586d58a3dbf045e178e"
            client_secret:    "b339f6c5ee20e03e8aa6b923c144efd9ae74ba0c" #"99225fedb2d3ce7044a61ee29e7e7cb8600f1bc0"
            scope:            "user:email"

        facebook:
            type:             facebook
            client_id:        "459203570901678" #"278935655649323"
            client_secret:    "0e479eac95041fc5a93d6817fd17da53" #"9005fb2aee66302e460da34160624002"
            scope:            "email,user_photos"

        google:
            type:             google
            client_id:        '423379035176-l6a5kt5uuj6fb8a4h4ohft5spit48pd1.apps.googleusercontent.com'
            client_secret:    'ifwL00BQeNh0BTimEwVHyISF'
            scope:            'https://www.googleapis.com/auth/userinfo.email'


