network_o_auth:
    resource: "@NetworkOAuthBundle/Resources/config/routing.yml"
    prefix:   /

network_user:
    resource: "@NetworkUserBundle/Resources/config/routing.yml"
    prefix:   /

network_web:
    resource: "@NetworkWebBundle/Resources/config/routing.yml"
    prefix:   /

network_store:
    resource: "@NetworkStoreBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /authorization

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
