network_import:
    resource: "@NetworkImportBundle/Resources/config/routing.yml"
    prefix:   /

network_oauth:
    resource: "@NetworkOAuthBundle/Resources/config/routing.yml"
    prefix:   /

network_user:
    resource: "@NetworkUserBundle/Resources/config/routing.yml"
    prefix:   /

network_web:
    resource: "@NetworkWebBundle/Resources/config/routing.yml"
    prefix:   /

network_store:
    resource: "@NetworkStoreBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
