network_web_socket:
    servers:
        default: # Server name
            listen: ws://vdolgah.org:8000 # default: ws://localhost:8000

            # Applications this server will allow
            applications:
                - echo


            # Origin control
            check_origin: true
            allow_origin: # default: just localhost (not useful!)
                - "localhost"
                - "vdolgah.org"

            # Other defaults
            max_clients:             30
            max_connections_per_ip:  5
            max_requests_per_minute: 50
