<?php

namespace Network\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Network\StoreBundle\Entity\Playlist;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class PlaylistRepository extends EntityRepository
{
    public function getAllUserPlaylists($userId)
    {
        $r = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('NetworkStoreBundle:Playlist', 'm')
            ->join('m.user', 'u')
            ->where('u.id = :userId' )
            ->setParameters(['userId'=> $userId])
            ->getQuery()
            ->getResult();

        return $r;
    }
}
