mainpage:
    path:     /
    defaults: { _controller: NetworkWebBundle:Default:index, name: 'stranger' }

network_web_homepage:
    path:     /hello/{name}
    defaults: { _controller: NetworkWebBundle:Default:index }

user_profile_editing:
    path: /user/{id}/profile/
    defaults: { _controller: NetworkWebBundle:User:profile }
    requirements:
       id: \d+

kladr_test_page:
    path:     /test/kladr
    defaults: { _controller: NetworkWebBundle:Kladr:test }

vkontakte_login:
    pattern: /login/check-vkontakte

vkontakte_connect:
    pattern: /connect/check-vkontakte

# smth_login:
#     path:     /login
#     defaults: { _controller: NetworkWebBundle:Auth:login }
