mainpage:
    path:     /
    defaults: { _controller: NetworkWebBundle:Default:index }

user_jobs_profile:
  path: /profile/jobs
  defaults: { _controller: NetworkWebBundle:User:jobs }

user_profile_json:
  path: /profile/json/jobPosts.get
  defaults: { _controller: NetworkWebBundle:User:json }
  methods: [POST]
  options:
    expose: true

audio_track_upload:
  path: /upload/audio
  defaults: { _controller: NetworkStoreBundle:AudioTrack:upload }
  methods: [POST]
  options:
    expose: true

audio_track_download:
  path: /download/audio/{id}
  defaults: { _controller: NetworkStoreBundle:AudioTrack:download }
  requirements:
    id: \d+
  options:
    expose: true

audio_player:
  path: /listen/{user_id}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:viewPlayer, user_id: null }
  requirements:
    user_id: \d+

audio_add_track_to_playlist:
  path: /playlist/{playlist_id}/push/{track_id}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:pushTrackToPlaylist}
  requirements:
    track_id: \d+
    playlist_id: \d+
  options:
    expose: true

audio_add_playlist:
  path: /playlist/add/{name}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:addPlaylist }
  methods: [POST]
  options:
    expose: true

audio_remove_playlist:
  path: /playlist/remove/{playlist_id}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:removePlaylist }
  options:
    expose: true

audio_get_all_playlists:
  path: /playlist/all/{user_id}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:getAllPlaylists, user_id: null }
  methods: [POST]
  options:
    expose: true
  requirements:
    user_id: \d+

audio_track_delete:
  path: /delete/audio/{audio_id}/playlist/{playlist_id}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:deleteAudioFromPlaylist }
  options:
    expose: true
  requirements:
    audio_id: \d+
    playlist_id: \d+

audio_search:
  path: /search/audio/{by}/{what}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:search }
  requirements:
    options: artist|title
  options:
    expose: true

audio_edit:
  path: /audio/edit/{audio_id}
  defaults: { _controller: NetworkWebBundle:AudioPlayer:edit }
  methods: [POST]
  options:
    expose: true
  requirements:
    audio_id: \d+

file_upload:
  path: /profile/upload/file
  defaults: { _controller: NetworkStoreBundle:File:upload }
  methods: [POST]

file_delete:
  path: /profile/json/file.delete
  defaults: { _controller: NetworkStoreBundle:File:delete }
  methods: [POST]
  options:
    expose: true

file_download:
  path: /download/{file_id}
  defaults: { _controller: NetworkStoreBundle:File:download }
  requirements:
    file_id: \d+

videos:
  path: /video/
  defaults: { _controller: NetworkWebBundle:VideoReference:index }

add_video:
  path: /video/add/
  defaults: { _controller: NetworkWebBundle:VideoReference:addVideoReference }

edit_video:
  path: /video/edit/{id}
  defaults: { _controller: NetworkWebBundle:VideoReference:editVideoReference }
  requirements:
    id: \d+

delete_video:
  path: /video/delete/
  defaults: { _controller: NetworkWebBundle:VideoReference:deleteVideoReference }
  methods: [POST]
  options:
    expose: true

bind_video:
  path: /video/bind/
  defaults: { _controller: NetworkWebBundle:VideoReference:bindVideoReference }
  methods: [POST]
  options:
    expose: true

wall_write:
  path: /{type}/id{id}/write
  defaults: { _controller: NetworkWebBundle:Wall:write }
  methods: [POST]
  requirements:
    type: user|club
    id: \d+
  options:
    expose: true

wall_delete:
  path: /{type}/id{id}/delete/{post_id}
  defaults: { _controller: NetworkWebBundle:Wall:delete }
  requirements:
      type: user|club
      id: \d+
      post_id: \d+
  options:
    expose: true

wall_load_posts:
  path: /{type}/id{id}/load/{start}
  defaults: { _controller: NetworkWebBundle:Wall:loadPosts }
  requirements:
    type: user|club
    id: \d+
    start: \d+
  options:
    expose: true
like:
  path: /like/write
  defaults: { _controller: NetworkWebBundle:Like:like }
  options:
    expose: true

like_count:
  path: /like_count
  defaults: { _controller: NetworkWebBundle:Like:getCount }
  options:
    expose: true

like_user:
  path: /like_user
  defaults: { _controller: NetworkWebBundle:Like:getUser }
  options:
    expose: true

user_poll_create:
  path:     /poll/
  defaults: { _controller: NetworkWebBundle:Poll:create }
  options:
    expose: true

user_poll_edit:
    path:     /poll{id}/edit
    defaults: { _controller: NetworkWebBundle:Poll:edit }
    requirements:
       id: \d+

user_poll_delete:
    path:     /poll{id}/delete
    defaults: { _controller: NetworkWebBundle:Poll:delete }
    requirements:
       id: \d+

user_poll:
  path:     /poll{id}/
  defaults: { _controller: NetworkWebBundle:Poll:poll }
  requirements:
    id: \d+
  options:
    expose: true

users_poll:
  path: /users/poll
  defaults: { _controller: NetworkWebBundle:Poll:getUserAnswerJson }
  options:
    expose: true
